'use strict'

const express = require('express')
const router = express.Router()

// 显式 require 所有模块。阶段 3 改用 routeLoader 自动扫描。
const authRoutes = require('@modules/auth/auth.routes')
const orgRoutes = require('@modules/org/org.routes')
const userRoutes = require('@modules/user/user.routes')
const positionRoutes = require('@modules/position/position.routes')
const studentRoutes = require('@modules/student/student.routes')
const subjectRoutes = require('@modules/subject/subject.routes')
const courseProductRoutes = require('@modules/courseProduct/courseProduct.routes')
const courseInstanceRoutes = require('@modules/courseInstance/courseInstance.routes')
const courseEnrollmentRoutes = require('@modules/courseEnrollment/courseEnrollment.routes')
const roomRoutes = require('@modules/room/room.routes')
const lessonScheduleRoutes = require('@modules/lessonSchedule/lessonSchedule.routes')
const orderRoutes = require('@modules/order/order.routes')
const studentProductRoutes = require('@modules/studentProduct/studentProduct.routes')
const lessonAttendanceRoutes = require('@modules/lessonAttendance/lessonAttendance.routes')
const studentWorkRoutes = require('@modules/studentWork/studentWork.routes')
const pointsRoutes = require('@modules/points/points.routes')
const petRoutes = require('@modules/pet/pet.routes')
const healthRoutes = require('@modules/health/health.routes')
const categoryRoutes = require('@modules/category/category.routes')
const regionRoutes = require('@modules/region/region.routes')
const schoolRoutes = require('@modules/school/school.routes')
const agentRoutes = require('@modules/agent/agent.routes')
const reportRoutes = require('@modules/report/report.routes')
const storageRoutes = require('@modules/storage/storage.routes')
// 招生试听 (2026-06 重构: Lead → Parent + ChildLead)
const parentRoutes = require('@modules/parent/parent.routes')
const childLeadRoutes = require('@modules/childLead/childLead.routes')
const trialBookingRoutes = require('@modules/trialBooking/trialBooking.routes')

router.use('/auth', authRoutes)
router.use('/orgs', orgRoutes)
router.use('/users', userRoutes)
router.use('/positions', positionRoutes)
router.use('/students', studentRoutes)
router.use('/subjects', subjectRoutes)
router.use('/course-products', courseProductRoutes)
router.use('/course-instances', courseInstanceRoutes)
router.use('/course-enrollments', courseEnrollmentRoutes)
router.use('/rooms', roomRoutes)
router.use('/lesson-schedules', lessonScheduleRoutes)
router.use('/orders', orderRoutes)
router.use('/student-products', studentProductRoutes)
router.use('/lesson-attendances', lessonAttendanceRoutes)
router.use('/student-works', studentWorkRoutes)
router.use('/points', pointsRoutes)
router.use('/pet', petRoutes)
router.use('/health', healthRoutes)
router.use('/categories', categoryRoutes)
router.use('/regions', regionRoutes)
router.use('/schools', schoolRoutes)
router.use('/agent', agentRoutes)
router.use('/reports', reportRoutes)
router.use('/storage', storageRoutes)
// 招生试听 (2026-06)
router.use('/parents', parentRoutes)
router.use('/child-leads', childLeadRoutes)
router.use('/trial-bookings', trialBookingRoutes)

module.exports = router
